baseURL = "https://blog.ingolonde.pw/"
disablePathToLower = true
languageCode = "ru-ru"
title = "Поток сознания"

theme = "henry"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

